### ISSUE TITLE
Why remove auto generated MSG ids?

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#102]
Some autogenerated (by src/clib/ncparser.pl) MSG ids were 
renamed/deleted in 8600910b76ef546407bb85e920419b065a4bd922 .

This change makes it difficult to use the ncparser.pl script to regenerate
pio_nc.c .

Why were these auto generated MSG ids removed (and why wasn't ncparser.pl
not modified accordingly?)? Are we not going to use ncparser.pl anymore?

**Comment by jayeshkrishna** [comment]
@edhartnett / @jedwards4b : Do you mind if I add these message ids back ?

**Comment by jedwards4b** [comment]
Either ncparser.pl needs to be updated or the msg id's need to be put back - Ed which do you prefer?

**Comment by jedwards4b** [comment]
I have a branch update_ncparser in git@github.com:jedwards4b/ParallelIO.git  which should fix the
MSG issues, but the resulting pio_nc.c is completely reordered so it's really hard to tell if I've unintentionally changed something else.

**Comment by jayeshkrishna** [comment]
Yeah, I had the same problem too (regenerating pio_nc.c from the version of netcdf/pnetcdf headers resulted in reordering of the code - so hard to detect if anything changed). 
@edhartnett : Do you know which version of libs you used when generating pio_nc.c in 6ff466c6cf3e4cd258452d0c677414af3c23c742 ?

**Comment by jayeshkrishna** [comment]
@jedwards4b : Since your change fixes ncparser.pl I vote to go with your change. If we can find the version of netcdf/pnetcdf libs that @edhartnett used to create the previous version of pio_nc.c I think we will be able to integrate your branch with minimal changes to the code base.

**Comment by edhartnett** [comment]
Jim, if you recall, the generated code, and ncparser.pl, is going to disappear as soon as we do a definitive merge of the async code.

So pio_nc.c will be replaced with what is now pio_nc_async.c.

I was hoping that we could eliminate confusion by doing the definitive switchover to the async version of the code as soon as I can sort out the issues with the current pull request.

In the new async code, there are many fewer messages, because the code relies on the redundancy of the netcdf api to only call the core functions, and treat all the variant functions as special cases of the core functions. For example, nc_inq_ndims, nc_inq_nvars, etc., which all call the core function nc_inq().

What I don't quite get is where did this start to impact non-async builds? I thought that I had only removed these numbers for async builds only. Was I mistaken about that?

**Comment by jayeshkrishna** [comment]
Although the MSG ids are used only for async cases whenever we use ncparser.pl to regenerate pio_nc.c we end up with the old MSG ids (unless we use @jedwards4b 's fix). 
From what you say it looks like we are not planning to use the parser any more, am I right?

**Comment by jayeshkrishna** [comment]
Also what about ncputgetparser.pl, are we planning to use it in future?

**Comment by edhartnett** [comment]
When the async code is fully merged, no code will be generated by perl scripts.

The put/gets were also very easy to reduce to one function for puts and one for gets. All other put/get functions are just special cases of PIOc_get_vars_tc/PIOc_put_vars_tc.

The only exception are the varm functions. Those I leave untouched. I suggested to Jim that they be removed, but he wants to keep them. (Those dang varm functions in netCDF have caused me problems for years!) Anyway, no one uses them, I hope. They do not work with the async interface.

**Comment by jayeshkrishna** [comment]
@edhartnett : A related question, will src/clib/pio_darray_async.c also replace src/clib/pio_darray.c (all *async* versions replace the corresponding sources)?

**Comment by edhartnett** [comment]
Yes, correct.
