### ISSUE TITLE
The init functions for rearranger options are no longer available

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#1042]
I was looking at the code and noticed that the initialization function for
the rearranger options has been deleted in the current master.

These functions were deleted in PR #957 . The PR description does not
suggest these functions were intended to be removed (and this PR was
not reviewed)

As discussed in PR #868 , having a separate function for initializing the
rearranger option structure is very useful for code clarity. Also without
the initialization function we cannot reset invalid combinations of user
arguments.

The new code that was added in PR #957  also has bugs.

**Comment by edhartnett** [comment]
Sorry, not clear why this code should be included.

Please specify more exactly any bugs in the code base.

**Comment by jayeshkrishna** [comment]
The original functions initialized all members of the structure (rearranger option structure) in a way that the values set were valid. For example, if the user chooses collective option for rearrangement we don't want the user to think about the values of the other arguments passed to the function that are not related to this option (fcd etc). The old code checked whether the user arguments passed in were valid and reset it to valid values if they were not (so if the user specifies COLL for rearrangement the user does not have to worry about values of fcd for example).
I would recommend bringing back the old init functions.
(In the current code when checking inputs to pioc_set_rearr_opts() comm_type is compared to  PIO_REARR_COMM_FC_1D_COMP2IO and there are some implicit assumptions about the values of enumerations there. Also the issue that I mentioned above with invalid combinations of user args.)

**Comment by edhartnett** [comment]
The custom in C libraries is that unused options are ignored. In other words, if the user specifies COLL for rearrangement, the code is smart enough to know that it cannot use the values of fcd.

If you wish to write a test that demonstrates that all invalid combinations of settings are rejected, and all valid ones are successfully handled (including ignoring the unused fields), that would be good. I wrote some C tests for rearranger functionality in test_rearr.c. Here's my test of the rearranger options - some invalid entries are tested, only one valid call:

```
/* Test some of the rearranger utility functions. */
int test_rearranger_opts1(int iosysid)
{
    iosystem_desc_t *ios;
    int ret;

    /* This should not work. */
    if (PIOc_set_rearr_opts(TEST_VAL_42, 0, 0, false, false, 0, false,
                            false, 0) != PIO_EBADID)
        return ERR_WRONG;
    if (PIOc_set_rearr_opts(iosysid, TEST_VAL_42, 0, false, false, 0, false,
                            false, 0) != PIO_EINVAL)
        return ERR_WRONG;
    if (PIOc_set_rearr_opts(iosysid, 0, TEST_VAL_42, false, false, 0, false,
                            false, 0) != PIO_EINVAL)
        return ERR_WRONG;
    if (PIOc_set_rearr_opts(iosysid, 0, 0, false, false,
                            PIO_REARR_COMM_UNLIMITED_PEND_REQ - 1, false,
                            false, 0) != PIO_EINVAL)
        return ERR_WRONG;
    if (PIOc_set_rearr_opts(iosysid, 0, 0, false, false, 0, false,
                            false, PIO_REARR_COMM_UNLIMITED_PEND_REQ - 1) !=
        PIO_EINVAL)
        return ERR_WRONG;

    /* This should work. */
    if ((ret = PIOc_set_rearr_opts(iosysid, PIO_REARR_COMM_P2P,
                                   PIO_REARR_COMM_FC_1D_COMP2IO, true,
                                   true, TEST_VAL_42, true, true, TEST_VAL_42 + 1)))
        return ret;

    /* Get the IO system info from the id. */
    if (!(ios = pio_get_iosystem_from_id(iosysid)))
        return pio_err(NULL, NULL, PIO_EBADID, __FILE__, __LINE__);

    /* Check the rearranger settings. */
    if (ios->rearr_opts.comm_type != PIO_REARR_COMM_P2P ||
        ios->rearr_opts.fcd != PIO_REARR_COMM_FC_1D_COMP2IO ||
        !ios->rearr_opts.comp2io.hs || !ios->rearr_opts.comp2io.isend ||
        !ios->rearr_opts.io2comp.hs || !ios->rearr_opts.io2comp.isend ||
        ios->rearr_opts.comp2io.max_pend_req != TEST_VAL_42 ||
        ios->rearr_opts.io2comp.max_pend_req != TEST_VAL_42 + 1)
        return ERR_WRONG;

    return 0;
}

```

By following C convention, and keeping this code out of the C library, we reduce on-going maintenance effort. By testing it in the test library, we achieve a lower cost because the test code is much cheaper to write and maintain.

More tests, in C or fortran, would be welcome.

In PIOc_set_rearr_opts() I believe you are referring to this line:

```
    /* Check inputs. */
    if ((comm_type != PIO_REARR_COMM_P2P && comm_type != PIO_REARR_COMM_FC_1D_COMP2IO) ||
        (fcd < 0 || fcd > PIO_REARR_COMM_FC_2D_DISABLE) ||
        (max_pend_req_c2i != PIO_REARR_COMM_UNLIMITED_PEND_REQ && max_pend_req_c2i < 0) ||
        (max_pend_req_i2c != PIO_REARR_COMM_UNLIMITED_PEND_REQ && max_pend_req_i2c < 0))
        return pio_err(NULL, NULL, PIO_EINVAL, __FILE__, __LINE__);        

```
This is indeed a fun line of code. ;-)

My recollection is that this is the logic which was happening in the previous code, condensed into one if statement. In other words, these were the conditions that previously caused errors. However I have not checked this recollection in the code.

If you can demonstrate a problem with some test code, that would be the best way to proceed.

**Comment by edhartnett** [comment]
Closing issue unless specific problem is demonstrated in test code.
