### ISSUE TITLE
Should there be one global cn_buffer_pool, or should each iosysid get a CN buffer?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#118]
Right now there is one cn_buffer pool for all open iosystems. Is that correct?

**Comment by jedwards4b** [comment]
There is only one buffer pool per task.   What advantage would there be in having each iosysid get a separate one?

**Comment by jedwards4b** [comment]
I think that the issue is should there be a separate buffer pool for each iosysid thus making it easier to manage a free call on the pool.   The difficulty is that you need to tune the size of the buffer pool to fit the memory requirements of the model and having one pool per iosysid may really complicate that tuning.

**Comment by edhartnett** [comment]
Just wanted to confirm this. I had to add code to finalize like this:

    /* Free the buffer pool. */
    int niosysid;
    if ((ierr = pio_num_iosystem(&niosysid)))
	return ierr;
    LOG((2, "%d iosystems are still open.", niosysid));

    /* Only free the buffer pool if this is the last open iosysid. */
    if (niosysid == 1)
    {
	free_cn_buffer_pool(*ios);
	LOG((2, "Freed buffer pool."));
    }

I had to add this code because when there was overlap between iosystems (i.e. one task part of 2 iosystems), and one of the iosystems is finalized, but on an iosystem that does not include all tasks. In that case, some tasks hung because of confusion over whether the buffer pool was null or not.

So I added the code above, which only frees the buffer pool if this is the last iosystem to be finalized.

I have no objection to leaving it as one buffer pool per task; I just wanted to make sure I am not breaking it. ;-)

**Comment by edhartnett** [comment]
I'm going to close this if no one has any further comments...

**Comment by jedwards4b** [comment]
I have a case where this isn't working, but I'm only seeing the problem on one platform so I think that it may be somewhat mpi implementation dependent (this is sgi mpt/2.15)  The issue is that each task has a different number of iosystems and the ios represented by the last iosystem on each task does not form a collective for which the MPI_Reduce calls in cn_buffer_report will work.    I think that to handle this correctly the call to cn_buffer_report at line 1624 of pio_darray_int.c needs to be changed to cn_buffer_report(ios, false) this will avoid the collective calls within.
