### ISSUE TITLE
Variations in download-path arrangements

### ISSUE THREAD

**Issue by cponder** [NCAR/ParallelIO#1369]
I have download scripts for various libraries, as part of an integrated system for building combinations of libraries and generating the associated modules.
One thing I've noticed with PIO is that the naming conventions have varied between versions

     https://github.com/NCAR/ParallelIO/archive/pio2_4_1.tar.gz
     https://github.com/NCAR/ParallelIO/archive/pio-2.3.2.tar.gz
     https://github.com/NCAR/ParallelIO/archive/pio2.0.28.tar.gz

i.e. whether "." or "_" is used as a separator or if there is a  "-" before the version number.
Are you planning to stick with the format of the latest release?

Otherwise I can write a more complex script that tests for each format.
Will the "pio2_4_1" & "pio-2.3.2" be the only variations I'll need to handle?

**Comment by jedwards4b** [comment]
I'm not sure where you got the release address for pio-2.4.1, it's:
https://github.com/NCAR/ParallelIO/releases/download/pio2_4_1/pio-2.4.1.tar.gz

We'll try to be consistent with names in the future.

**Comment by edhartnett** [comment]
There are a few complexities. We actually are consistent in our naming, at
least for the PIO 2.x versions.

When we do a release on github, for the PIO 2.x versions, we use a tag like
this: pio2_4_1. Github then generates a .zip and .gz distribution file,
like this: https://github.com/NCAR/ParallelIO/archive/pio2_4_1.tar.gz.

But this is not a proper distribution, it is just a packaging of the repo
that github does. It works for cmake however, because all the cmake stuff
is in the repo.

In order to get an autotools tarball, I do a make dist and upload the
result to github, which looks like this:
https://github.com/NCAR/ParallelIO/releases/download/pio2_4_1/pio-2.4.1.tar.gz.
(And this is the standard way of naming unix package tarballs, with dots
not underscores.)

Currently the autotools build is C library only but I am adding fortran as
well.

When that happens you may wish to switch to the autotools build, and that
will be fine. Until then, you want to stick with the cmake build, which has
underscores.

Ed

**Comment by cponder** [comment]
Here's a new one:

https://github.com/NCAR/ParallelIO/releases/download/pio**_**2_5_1/pio-2.5.1.tar.gz
https://github.com/NCAR/ParallelIO/releases/download/pio2_5_2/pio-2.5.2.tar.gz

There's a difference in the underscoring between pio**_**2_5_1  --> pio2_5_2
