### ISSUE TITLE
shall we introduce error mode PIO_REDUCE_ERROR?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1424]
Once change proposed in #1410 is the addition of a new error handling code: 

```
/** Error codes are reduced across all processes. */
￼     PIO_REDUCE_ERROR = (-53),

```

The code for this is in pioc_support.c, starting at line 534.

@jedwards4b the question is, do we add this error handler or not?

@jayeshkrishna can you give us an idea of how this is helpful?

**Comment by jayeshkrishna** [comment]
This error handler would be useful in detecting errors across all MPI processes - https://github.com/E3SM-Project/ParallelIO/pull/146

**Comment by jedwards4b** [comment]
These error handlers are intended for use in user code on compute tasks.  PIO already reduces errors to io task 0 before returning to the compute space so I don't think that any new functionality is added with this change.   @jayeshkrishna Is there something I'm missing?   Can you give an example of where this would need to be used in a user code instead of PIO_BCAST_ERROR?

**Comment by jayeshkrishna** [comment]
This error handler should be able to capture errors in the non-root I/O procs, capture multiple error codes from different I/O procs etc. This is intended for developers debugging issues in PIO (not production).

**Comment by edhartnett** [comment]
OK, I believe we have decided not to proceed with this.

In terms of debugging PIO, I find the current error handlers work as well as I could wish. When my test program crashes, I get the error from ioproc 0 and that tells me the line and source file, and that's what I need.
