### ISSUE TITLE
decomposition file

### ISSUE THREAD

**Issue by wkliao** [NCAR/ParallelIO#1878]
I have the following question regarding to the decomposition file.
There can be zero values in the offset index lists, which are meant to be ignored.
I am curious why these zeros were added in the first place, and wondering
they may serve some purposes. Please let me know.

**Comment by jedwards4b** [comment]
Hi @wkliao the zero values can be used to mark halo points or other points outside the domain of interest in an array to be written.

**Comment by wkliao** [comment]
Thanks, Jim
When writing data to NetCDF files, does PIO save these data points in separate NetCDF variables?

**Comment by jedwards4b** [comment]
No - they are simply ignored.

**Comment by wkliao** [comment]
I assume those data points are still to be used by some post-simulation software, but
the software retrieves those data point locations from parsing the decomposition files,
instead of reading from NetCDF files. Is this correct? If yes, it looks like the simulation
application also output the decomposition files, as part of its I/O activity.

FYI. I am developing an I/O benchmark program to study the I/O performance of E3SM
and hope not to miss any I/O activities.

**Comment by jedwards4b** [comment]
@wkliao those points are only in the decomp files and the decomp files only exist so that you can create a faithful reproduction of model io patterns offline, as far as I know there are no postprocessing tools that would use that information.   The pioperformance.F90 is the only tool that uses the decomp files - I would invite you to consider using and building upon that tool for your I/O benchmark program.

**Comment by wkliao** [comment]
I see. Thanks for the information.
I believe my benchmark program has already captured the essence of
pioperformance.F90 as well as E3SM's. FYI. it is in [E3SM-IO](https://github.com/Parallel-NetCDF/E3SM-IO) github repo.

**Comment by wkliao** [comment]
Thanks, Jim! Close this issue.
