### ISSUE TITLE
Fortran interface for async init

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#241]
Fix the fortran interface for async init to call the right C async init function.

**Comment by edhartnett** [comment]
The async init in C is going to change. (And I would welcome feedback.)

The previous interface required a lot of the setup work to be done by the user.

So I added a new function which does a lot more of the work, but it does not pass out pointers to the communicators it creates, and it should, because the calling program sometimes needs them.

It also currently lumps information about the IO component with the computation components. I think it would be better if they were kept separate.

So just a heads-up that the init async code is not yet finalized.

**Comment by edwardhartnett** [comment]
Thanks to Jim, this is now done.
