### ISSUE TITLE
Use "next" branch for PIO

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#266]
The master branch was broken last night with 50+ failed tests, see #264. I think it would be useful to create a branch called "next" or "develop" for testing open PRs. When a PR is approved, it will be merged to the next branch first for testing before merged to master. This can maintain a more stable master branch. As far as I know, ACME and PETSc do use a next branch.

**Comment by edhartnett** [comment]
It was my change that broke the tests. I'll have a fix shortly, BTW.

I have worked on projects with both a 'develop' and 'master' branch. I am willing to go to such a system.

Another alternative (which I believe you could set up on your Jenkins build), is that Jenkins builds PRs, which accomplishes the same thing.

I am happy with either approach. If we are creating a "develop" branch, it would be good if we could wait for me to finish two open branches I have. Perhaps we could plan to do it Monday. 

If you want to try the Jenkins PR builder, I have never used it but it is being used on the NetCDF project with great success. I believe i saw it in the plugins list in Jenkins. I believe you just install the plugin and turn it on for the project.

**Comment by rljacob** [comment]
The advantage of a "devlop" or "next" branch is it allows you to check multiple PRs at once to look for side effects.   Not a problem is we typically have 1 PR per day or less.  But there have been bursts of multiple PRs per day recently.

A stable master should be paramount.

**Comment by edhartnett** [comment]
For the last few months we have had usually more than 1 PR per day. I usually do at least 2 a day, as Jim can attest, because he looks at my changes.

So I think a develop branch would be a good thing and I will set one up after I complete the current changes I have underway. Probably Monday. If there are any other programmers who would like me to wait, please let me know.

We can continue code development, review, and testing on the develop branch, and periodically merge it to master after the code has passed all tests on the develop branch.

**Comment by jedwards4b** [comment]
So we will duplicate all the testing we are doing on master with another branch and continue to test master as well?   Okay I'm willing to try it.

**Comment by Katetc** [comment]
I like this idea a lot because it gives everybody a chance to see the automated tests run on new code across platforms. However, I'm not entirely sure our current cdash setup will like it. We'll probably need to either add information to the build name tag or make use of the "Experimental" vs "Nightly" builds. We can look into it next week.

**Comment by gold2718** [comment]
If all new work goes into 'develop' before getting merged to master then all merges to master should be FF, correct? If so, I don't  see why master needs nightly testing.
I suggest that master is manually tested after a merge (which could be much less than once per day) and that we move towards a possibly more extensive pre-tag like testing for these merges.
That way, master is always stable and updates bring in whole bug fixes and/or new features.

**Comment by gold2718** [comment]
Another issue raised by a develop branch is the need for a history policy. I think the pull request document should state either that there is no history rewrite, or that merges to master use a squashed history providing better documentation of the merge. I don't have a problem either way but think it should be documented.

**Comment by edhartnett** [comment]
I would also want to see master tested automatically every day, with a variety of build options.

I think for CDash if it is hard to set up tests for two branches, then probably it should test the develop branch, where all the work is happening.

**Comment by rljacob** [comment]
Cdash should allow you to report as much as you want.  In acme, we set the build name to "testsuite_branch_compiler" to help tell entries apart.  You have to tell Jenkins to check out and run tests on each branch.

The workflow for this is to merge your feature branch twice: once in to develop, wait for testing to pass, and then once in to master.  Each time the merge should NOT be a FF merge. You make a PR request for a merge to master before stating anything.  Never merge develop to master because develop may have features which didn't "graduate" or are not ready to graduate and need more testing.

**Comment by edhartnett** [comment]
We have started this, and are working on the process on another ticket. So I am going to close this one.
