### ISSUE TITLE
pio_unit_test failure

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#276]
It is observed that pio_unit_test fails recently, which  is related to an assertion failure:
pioc_support.c:366: check_netcdf: Assertion `file' failed.

In PIOc_deletefile(), pio_file.c, there is a pointer of file_desc_t type, which is define but never initialized or assigned:
file_desc_t *file;

Therefore, with different compilers or environments, this pointer can be a junk value or NULL.

The failure seems to be introduced by commit 1372ba5, which added a check like below:
check_netcdf(file, ierr, \__FILE\__, \__LINE\__);
When the file pointer happens to be NULL, the assertion in check_netcdf() fails.

Not all builders can catch this failure caused by uninitialized/unassigned variable: 
On CDash, it only fails for gcc 4.8.5 and PGI 16.5
On ANL Jenkins server, it only fails for valgrind check builder (not for coverage builder)

Suggestion:
1) This pointer should be explicitly initialized to NULL, or assigned with a valid value.
2) check_netcdf() should not be called if this pointer is NULL.

**Comment by dqwu** [comment]
Another issue is that check_netcdf() defined in pio_support.c might fail to report a expected failure to ctest (or make check)

I tested on one ANL workstation, the file pointer got a junk value like 4078a4, this will go to the default branch of switch-case
    default:
        ierr = iotype_error(file->iotype,\__FILE\__,\__LINE\__);

It correctly printed out the error in the log:
ERROR: iotype 1238417607 not defined in src/clib/pioc_support.c 406

However, this test still "passed", as check_netcdf() still returns 0 (the status variable), instead of PIO_EBADIOTYPE

**Comment by gold2718** [comment]
It seems to me that this is one of the reasons why every variable in C should always be initialized. Since the advent of ANSI C, there is no reason for a variable to exist (be in scope) if it doesn't have a value.

**Comment by dqwu** [comment]
Unfortunately, even if check_netcdf() can return an error code and PIOc_deletefile() returns this code as well, the test will still pass. 

Inside test_create() which is defined in basic_tests.F90, PIO_deletefile is a subroutine, not a function like PIO_createfile that can have a return value for checking.

Is there a reason that for Fortran version we do not have return values from PIO_deletefile?

**Comment by jayeshkrishna** [comment]
I think it is a bug that the fortran version (pio_deletefile) does not return an error code.

**Comment by edhartnett** [comment]
As is so often the case, confusion ensues because multiple bugs are interacting.

I am writing a check_netcdf2() which will solve the problems in that function. It must take an iosystem_desc_t pointer, and a file_desc_t pointer, and must be prepared if either or both are NULL.

I also agree that it's a bug that the fortran deletefile is not a function, so cannot return an error code. I will leave it to you fortran guys to fix that one.

Problems of incorrectly initialized values cannot be solved by a simple rule like initialize all the variables. If the variables in check_netcdf() had been initialized, it still would not have operated correctly, but we might not have noticed.

I have in mind some good tests to add for our error handling in the C library, in future PRs.
