### ISSUE TITLE
pio_seterrorhandling problem

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#375]
The code in
git@github.com:jedwards4b/ParallelIO.git
   c6b6b98..98d1ba6  jpe/error_handling

demonstrates a problem in pio_seterrorhandling.   In this code in test ncdf_inq I have added a call to 
pio_inq_varid for a variable that does not exist.  Just adding this in the original test works, however if
I comment out the call to pio_seterrorhandling at line 172 of pio_tutil.F90 and instead place it at 
line 93 of ncdf_inq.F90.in  (just before the call to pio_inq_varid) it fails to update the iosystem or the file error handling flag and so the code aborts on the call to pio_inq_varid.     This is a critical issue that must be addressed to test the code in CESM.

**Comment by edhartnett** [comment]
OK, I will take a look and fix quickly, but probably not til next week. ;-)

**Comment by edhartnett** [comment]
OK, here's what's happening. I think I see what I did wrong and how to fix it.

In the past, there was no file error handling. The iosystem error handling was just used in all cases. I had to add a variable to the file struct in order to also keep track of the file handling. So that is what changed.

When you open a file, the file error handler gets set to the current value of the iosystem error handler. (In your case it gets the default, PIO_INTERNAL_ERROR, unless you have changed it.)

Then you change the iosystem error handler, and cause an error on the file.

But the file error handler has not changed. And the file error handler takes precedence over the iosystem error handler.

What I need to do is let the file error_handler remain uninitialized. So unless you specifically set the error hanlding of the file, the iosystem error handling is used, and the current setting is used. That's probably what you intended.

So I will make those changes and submit a PR...

**Comment by jedwards4b** [comment]
I don't see how that could work.  What you are proposing would allow you to change the file error_handler once, but then how would you change it again.   It's not clear to me what value there is in having different error handlers for each file instead of just the one associated with the iosystem?

**Comment by jedwards4b** [comment]
Yes that is what I originally intended.   The two interfaces are there so that the user can use either the iosystem pointer or the file pointer to set the error_handling flag just as a convenience.   I can't think of a benefit of having separate handlers.  Typical usage in cesm (and this may only be because I wrote the interfaces) is to by default use PIO_INTERNAL_ERROR and only set PIO_BCAST_ERROR in cases where you might expect an error returned, setting it back to PIO_INTERNAL_ERROR right after checking the return code for the particular call. There are only a few cases in which the models expect a non-zero return code and are prepared to handle it, in most cases if an error occurs it's fatal and PIO_INTERNAL_ERROR reporting and aborting is what we want.

**Comment by edhartnett** [comment]
OK, stand by, I will fix.

So why do we need PIOc_Set_File_Error_Handler?

It is the same as calling PIOc_Set_Iosystem_Error_Handler but with file->iosystem instead of file.

**Comment by jedwards4b** [comment]
It's just a convenience - sometimes in user code you have a file pointer but not an iosystem pointer available in the place where you make the call.  In the fortran interface the user has pio_set_error_handling which can take either an iosystem or file pointer and the set_file and set_iosystem are internal functions which are not exposed to the user.  I think the confusion came in the translation to c.

**Comment by edhartnett** [comment]
OK, we should remove the function PIOc_Set_File_Error_Handling() from the C library. It is very misleading. And it provides no extra convenience (since if file is available, so is file->iosystem).

If you wish to keep it in the fortran library, that's not a problem for me, but I think that's incorrect as well.

Not only does the name strongly and incorrectly indicate that there is a file error handler (in addition to the iosystem error handler), but also PIOc_Set_File_Error_Handling() will change the error handling for the entire IO system, even other files that are open at the time. If you have a function that applies to a file, and then you apply it's changes silently to a bunch of other files, that's very misleading.

**Comment by jedwards4b** [comment]
I don't think that we want an interface that requires the user to use the internal objects in the file
pointer.   That is file should be opaque and the user should never access file->iosystem.

You could provide a function get_iosystem(file)

**Comment by edhartnett** [comment]
OK, fair point.

I think your suggestion of a PIO_get_iosystem(file) function might be the best answer. Let me ponder...
