### ISSUE TITLE
Clean up API and documentation of PIOc_Init_Async()

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#402]
In pioc.c, PIOc_Init_Async() has a description for its parameters:
```
 * @param num_procs_per_comp an array of int, of length
 * component_count, with the number of processors in each computation
 * component.

 * @param proc_list an array of arrays containing the processor
 * numbers for each computation component.
```
From the function body and unit tests that calls this function, num_procs_per_comp is of length component_count + 1 (including an IO component before computational components).
The example below is from test_async_3proc.c
```
 /* Num procs for IO and computation. */
 int num_procs[NUM_COMBOS][COMPONENT_COUNT + 1] = {{2, 1}, {1, 2}};
```

For proc_list, it should also include an IO component. When the code creates one if the user did not provide it, the IO component is counted (component_count plus 1)
```
/* Allocate space for array of arrays. */
if (!(my_proc_list = malloc((component_count + 1) * sizeof(int *))))
    return pio_err(NULL, NULL, PIO_ENOMEM, __FILE__, __LINE__);
```

**Comment by edhartnett** [comment]
I believe I must change the API a little to make it more clear. Even I don't understand any more when I should add 1 to the size of arrays when dealing with computation and IO components.

Instead of dealing with the IO component as a special case of the computation component, I believe it will work better if I just separate that code and stop trying to store IO component information in arrays that otherwise hold computation component information.
