### ISSUE TITLE
Clean up pio_msg.c

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#485]
There are a few minor issues on pio_msg.c
1) Some unused local variables.
For example:
```
int inq_att_handler(iosystem_desc_t *ios)
{
   ...
   int *op, *ip;
   ...
}
```

2) Extra "\n" at the end of LOG statements, like:
`LOG((1, "create_file_handler got parameter len = %d\n", len));`

3) Wrong comment. In the code below the function is to write the attribute, not read.
```
 /* Call the function to read the attribute. */
if ((ret = PIOc_put_att(ncid, varid, name, atttype, attlen, op)))
    return pio_err(ios, NULL, ret, __FILE__, __LINE__);
```

4) Some handlers are doing read/get operations. If the data acquired is actually not used, why do we need to call the APIs?
The following handler reads the attribute data in allocated memory, but the data read is never used.
```
int att_get_handler(iosystem_desc_t *ios)
{
    ...
    /* Allocate space for the attribute data. */
    if (!(ip = malloc(attlen * typelen)))
        return pio_err(ios, NULL, PIO_ENOMEM, __FILE__, __LINE__);

    /* Call the function to read the attribute. */
    if ((ret = PIOc_get_att(ncid, varid, name, ip)))
        return pio_err(ios, NULL, ret, __FILE__, __LINE__);

    /* Free resources. */
    free(ip);

    return PIO_NOERR;
}
```

**Comment by edhartnett** [comment]
OK, thanks. I have some changes to pio_msg.c up right now, and so do you, so lets get everything merged to master then I will hit this issue on a new task.

**Comment by edhartnett** [comment]
I have a PR up now with fixes for 1, 2, and 3.

As to 4, that is more complicated. ;-)

Those functions are called on the IO nodes, and their arguments need to match what was called on the computation nodes. For example, if the computation node calls PIOc_get_vars_int() it must provide a valid pointer for the data to be copied to.

The same is true in pio_msg. It must provide a valid pointer where the computation task caller did. Inside the call to the PIOc_get_vars function, the data will be copied to the computation nodes.

The data returned to the IO nodes is otherwise ignored. But the space needs to be there, because it is copied there from disk, and the MPI sends it from there to the computation nodes.

Jim, did I get it right?

**Comment by edhartnett** [comment]
OK, that PR is merged and I believe this issue can be closed.
