### ISSUE TITLE
Pass NC_MAX_NAME to Fortran

### ISSUE THREAD

**Issue by dqwu** [NCAR/ParallelIO#554]
In #319, it is noticed that:
1) pnetcdf defines NF_MAX_NAME and NC_MAX_NAME differently (128 vs 256)
2) The Fortran application can only see PIO_MAX_NAME (defined via NF_MAX_NAME in pio_types.F90)
3) The PIO C library would use PIO_MAX_NAME defined via NC_MAX_NAME

NC_MAX_NAME is defined in pnetcdf.h but that header file contains more information so it cannot be directly included in pio_types.F90 (will cause some compiler errors)

One possible solution is to modify CMake files of PIO, such that C macros like NC_MAX_NAME can be extracted and saved to a header file generated by CMake, which can then be included in pio_types.F90.

**Comment by jayeshkrishna** [comment]
Isn't there an issue already for this?

**Comment by dqwu** [comment]
@jayeshkrishna 
It is from #319, but I think it is better to create a new issue as this enhancement is more general.

**Comment by jayeshkrishna** [comment]
In that case please close the old issue and indicate that this issue follows it.

**Comment by wkliao** [comment]
I just noticed this ticket.
NF_MAX_NAME defined in PnetCDF should be the same as NC_MAX_NAME. I consider this is a PnetCDF bug. However, because NF_MAX_NAME is not used anywhere in PnetCDF internally, we have not encountered a problem before. I plan to make another PnetCDF release 1.8.1 as this bug seems serious enough. There will be a similar fix for a few other fortran 77 parameters, including nf_max_dims, nf_max_attrs, and nf_max_vars. Please see https://trac.mcs.anl.gov/projects/parallel-netcdf/changeset/2851

Please note unlike F77, the F90 corresponding parameters, nf90_max_name, nf90_max_dims, nf90_max_attrs, and nf90_max_vars, are kept up-to-dated with NetCDF and their corresponding C constants in PnetCDF. You might use them in PIO.

In principle, PnetCDF uses the same constant values defined in NetCDF, including C, F77, and F90, and they should be consistent among these languages. If you found any other mismatch in PnetCDF, please do not hesitate to let me know.

**Comment by dqwu** [comment]
@jayeshkrishna 
According to Release Note of PnetCDF 1.8.1:
Fortran parameters NF_MAX_DIMS, NF_MAX_ATTRS, NF_MAX_VARS, and NF_MAX_NAME defined in the Fortran header file, pnetcdf.inc, were set to obsolete values and have been fixed in this release to conform with their corresponding C constants. Because these four parameters were not used by PnetCDF internally, the end users can safely skip this release and 1.8.1 should perform the same as 1.8.0. If your programs explicitly use these four parameters, then updating to 1.8.1 is recommended.

**Comment by jayeshkrishna** [comment]
@dqwu : looks like you are verifying pio2+pnetcdf 1.8.1 builds with ASAN. Please update this issue with your findings.
Also pinging @edhartnett

**Comment by dqwu** [comment]
@jayeshkrishna 
I tested ASan build (on latest master branch ) with pnetcdf 1.8.1 and all the tested passed, including pio_unit_test.
