### ISSUE TITLE
Cleanup fillvalue handling in pioc_write_darray

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#612]
The fillvalue handling (when user hasn't passed a fillvalue) can
be cleaned up with a simple function to find fillvalues for MPI types.

**Comment by edhartnett** [comment]
I am working on these issues now so please don't make changes to this code until I am done. Thanks.

**Comment by jayeshkrishna** [comment]
What is the issue number that you are working on?

**Comment by edhartnett** [comment]
I am working towards #83.

In order to address it I had to do a bunch of work for fill values, including #405, #578, #547.

I have a fix for #568 which I am about to put up.

I still have to also finish #580 and #572.

Actually the bulk of the work was writing good tests. Now that I have those I think I will finish the rest of the fill value work this week.

As we agreed under #83 the current plan is that we will look up fill value with PIOc_inq_var_fill(). (We will store the result so we don't do the lookup every write operation, only the first.). If the user passes NULL for the fill value, we will provide it for them. If they pass a fill value we will compare it, and return an error (PIO_EINVAL). The caller can then fix or remove their fill value and try again.

**Comment by jayeshkrishna** [comment]
Which of these issues address (mention) the code refactoring suggested in this issue?

**Comment by jayeshkrishna** [comment]
Ok, so I can hold off on this refactoring until you are done with the issues above.

**Comment by edhartnett** [comment]
I suppose that if the explanations in my tickets do not apply to what you have in mind, you better explain it more fully. 

From your title and current explanation I get the idea that it might be related to fill values and the pio_write_darray() function, which may be related to the fill value work I have been doing, and also mentioned in the title of issue #83.

Please describe your suggested changes more fully. Thanks.

**Comment by jayeshkrishna** [comment]
I will wait for your issues to complete before proceeding with any changes.

**Comment by edhartnett** [comment]
I have just started working on this code, adding some logging statements. But I am working on darrays, decompositions, and making them both work with async. Some changes to PIOc_write_darray() will need to be made.

**Comment by edwardhartnett** [comment]
OK, I think this issue may be closed. I don't believe there is any further work happening with fill values handling.
