### ISSUE TITLE
Using a different type name for bufsize

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#615]
bget defines the name of the type to hold the buffer size as "bufsize".
And this type is used in the PIO2 source too.

The name does not sound like a typename (more like a variable name).
We could change it to something that sounds more like a type, bufsize_t ?

Code refactoring : No change in behaviour expected

**Comment by edhartnett** [comment]
What code file are you referring to? bget.c? Or some other file?

I have not touched bget.c in any way, since it is not our code. (That doesn't mean we shouldn't make changes, but we should first check the source to see if there is a more recent version that we should use as a starting point.)

For any code refactoring I expect you may want to also add to the unit tests. Although we are up to %80 code coverage, that still leaves a lot of room for better testing.

**Comment by jayeshkrishna** [comment]
bget.h defines the type and it is used else where (outside bget.c) in PIO2.
