### ISSUE TITLE
Non-Fortran build

### ISSUE THREAD

**Issue by gsjaardema** [NCAR/ParallelIO#63]
It does not look like it is possible to build a C-only (no Fortran) version.  Is that the case, or am I overlooking a configuration option?

**Comment by edhartnett** [comment]
I believe that is correct.

I agree that a C-only build would be helpful. Also an automake build is really necessary. So probably, like netCDF, we are going to have to maintain two build systems if we want to keep CMake.

However, I would suggest switching to automake and dropping CMake. The big advantage of CMake is in building on Windows platforms. I'm not even sure if MPI is available for Windows, or that any Windows user would use PIO.

(There are many Windows netCDF programs, but they access data sequentially.)

**Comment by edhartnett** [comment]
Turns out I needed this in order to help with some other issues, which I have to fix in the C library, but not necessarily the Fortran library (example: building without pnetcdf). So I need to be able to build the C library only.

I am doing this with modifications in the CMake files, using the existing (but previously not working) PIO_ENABLE_FORTRAN option.

PR will be up for review shortly.
