### ISSUE TITLE
Is PIOc_write_darray_multi() intended to be a public function?

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#692]
PIOc_write_darray_multi() is called (at sync) after the user calls PIOc_write_darray() one or more times.

Do we intend that the user should also call PIOc_write_darray_multi()?

Right now it is in the public API. Should it be?

**Comment by edhartnett** [comment]
On closer inspection it seems that this should not be a public function. Perhaps it was at one time, before aggregation was enabled, but now that aggregation is enabled, it is redundant. It allows the user to do aggregation semi-manually.

So I will remove to the private API, and change the inputs to pass pointers to ios and file, instead of ncid and iosysid, etc, and otherwise make this an internal function.

**Comment by jedwards4b** [comment]
Yes the idea was to expose this in the public interface so that the application developer could implement variable buffering outside of pio, in some cases the application is already buffering and the developer could avoid the extra memory usage.   Why not continue to allow this by keeping it public?

**Comment by edhartnett** [comment]
OK, I can live with that if you want.

I will change the docs to reflect this...
