### ISSUE TITLE
Now some tests fail with USE_MALLOC...

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#885]
Well I hope and believe are are circling in to the correct solution. ;-)

Our bget based builds are now working OK, but the malloc build is failing. I will take a look...

**Comment by jedwards4b** [comment]
I know what the problem is here and need to think about the fix.   The issue is that pnetcdf does a non-blocking write using ncmpi_iput and the iobuf must be retained until the waitall is completed. 
This means that the code as currently structured requires a flush between writes of multiple frames of the same variable.   But it could be that iobuf is not filled on all iotasks so simply testing whether iobuf is not NULL is not adequate.

**Comment by edhartnett** [comment]
I agree and I am wondering if this is not a new leak, but has just been undetected until now.

**Comment by jedwards4b** [comment]
I think that it's been there a while.

**Comment by edhartnett** [comment]
BTW if I take out the asserts that vdesc->ioregion is NULL, then the tests pass (but there are some memory leaks.) I think that's an improvement on the current situation, so I am going to put that up as a PR.

I don't think we should rely on pointers being reset to NULL after they are freed.

**Comment by jedwards4b** [comment]
No need - I've got the fix coming soon.
