### ISSUE TITLE
Test build with openmpi

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#906]
I am still getting my environment all sorted out with openmpi...

**Comment by jedwards4b** [comment]
We are now running with openmpi-2.0.2 on hobart and reporting to cdash.   However a number of tests are failing - digging into the test_darray failure today I see this at the end of the test output
```
ERROR: 0 NetCDF: Write to read only err_num = -37 fname = /home/jedwards/pio/src/clib/pio_darray.c line = 347
		0 pio_err chose error handler = -53
0 Closing the sample data file...
	0 PIOc_closefile ncid = 17
		0 pio_get_file ncid = 17
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10626,1],3]
  Exit code:    88
--------------------------------------------------------------------------
```
Looking at another build that works I see that there is an error expected at that point but it doesn't cause an mpi abort - so i think maybe the problem is just in the way that we invoke mpirun - but I've been looking around trying to figure out how to provide some other user-direction and haven't found anything.   Any ideas?

**Comment by edhartnett** [comment]
The test code, even when testing for error handling, never returns a non-zero error code.

That is, if all test code works, and code that does not work returns the correct error codes, then the test (all tasks) will return 0.

I would like to see the logging output for this. Is it available somewhere?

**Comment by edwardhartnett** [comment]
I have just started testing with github actions using openmpi-4.0.4.

**Comment by edwardhartnett** [comment]
OK a first pass at openmpi testing has been running for some time. It can be found here:
https://github.com/NCAR/ParallelIO/blob/master/.github/workflows/a3.yml

This tests the autotools and cmake builds with openmpi.

No doubt we will improve our testing over time, but I will call this issue closed for now.
